'use client';

import { useState } from 'react';
import { Bell, Check, ChevronDown, ChevronRight, Clock3, Droplets, HeartPulse, Home, Leaf, Menu, Moon, MoreHorizontal, Pill, Plus, Salad, Settings, Sparkles, TrendingUp, UserRound, Utensils, X } from 'lucide-react';

type Task = { id: number; icon: 'pill' | 'meal' | 'water' | 'walk' | 'sleep'; title: string; detail: string; time: string; done?: boolean };
const taskIcons = { pill: Pill, meal: Utensils, water: Droplets, walk: HeartPulse, sleep: Moon };
const initialTasks: Task[] = [
  { id: 1, icon: 'pill', title: 'Morning medication', detail: '40 min before breakfast', time: '6:10 AM', done: true },
  { id: 2, icon: 'meal', title: 'Breakfast', detail: 'Moong dal chilla + curd', time: '6:50 AM', done: true },
  { id: 3, icon: 'water', title: 'Morning hydration', detail: '500 ml before college', time: '7:00 AM', done: true },
  { id: 4, icon: 'pill', title: 'Evening medication', detail: 'Reshape Slimgal · before food', time: '6:20 PM' },
  { id: 5, icon: 'walk', title: 'Gentle evening walk', detail: '20 minutes · easy pace', time: '7:10 PM' },
  { id: 6, icon: 'meal', title: 'Dinner', detail: 'Jain paneer bowl + roti', time: '7:40 PM' },
  { id: 7, icon: 'sleep', title: 'Wind down', detail: 'Prepare medicines for tomorrow', time: '10:15 PM' },
];
const nav = [
  { label: 'Today', icon: Home }, { label: 'Plan', icon: Salad }, { label: 'Track', icon: HeartPulse }, { label: 'Medicines', icon: Pill }, { label: 'Insights', icon: TrendingUp },
];

export function Dashboard() {
  const [tasks, setTasks] = useState(initialTasks);
  const [active, setActive] = useState('Today');
  const [water, setWater] = useState(1250);
  const [snoozed, setSnoozed] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const completed = tasks.filter((task) => task.done).length;
  const percent = Math.round((completed / tasks.length) * 100);
  const nextTask = tasks.find((task) => !task.done) ?? tasks[tasks.length - 1];
  const completeTask = (id: number) => { setTasks((current) => current.map((task) => task.id === id ? { ...task, done: true } : task)); setSnoozed(false); };

  return <main className="min-h-screen bg-background text-foreground">
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-[248px] flex-col border-r border-border bg-[#f7f8f4] px-5 py-6 lg:flex">
      <Brand />
      <nav className="mt-10 space-y-1" aria-label="Main navigation">{nav.map((item) => <button key={item.label} onClick={() => setActive(item.label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition ${active === item.label ? 'bg-white text-primary shadow-[0_1px_8px_rgba(36,57,45,.07)]' : 'text-muted-foreground hover:bg-white/60 hover:text-foreground'}`}><item.icon size={18} strokeWidth={1.8} />{item.label}</button>)}</nav>
      <div className="mt-auto rounded-2xl bg-[#e9f1df] p-4"><div className="mb-3 flex h-9 w-9 items-center justify-center rounded-full bg-white text-primary"><Leaf size={17} /></div><p className="text-sm font-semibold text-[#294333]">A gentle reminder</p><p className="mt-1 text-xs leading-relaxed text-[#5d7064]">Consistency grows one small choice at a time.</p></div>
      <button className="mt-4 flex items-center gap-3 px-3 py-2 text-sm text-muted-foreground"><Settings size={17} /> Settings</button>
    </aside>
    <div className="lg:pl-[248px]">
      <header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-border/70 bg-background/90 px-5 backdrop-blur md:px-8 lg:px-10">
        <div className="lg:hidden"><Brand compact /></div><p className="hidden text-sm text-muted-foreground lg:block">Tuesday, September 8</p>
        <div className="flex items-center gap-2"><button aria-label="Notifications" className="relative flex h-10 w-10 items-center justify-center rounded-full border border-border bg-white text-muted-foreground hover:text-foreground"><Bell size={18} /><span className="absolute right-2.5 top-2 h-1.5 w-1.5 rounded-full bg-[#e68d68]" /></button><button className="ml-1 flex items-center gap-2 rounded-full pl-1 pr-2 text-sm font-medium"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#f0d8c3] text-[#714b38]"><UserRound size={18} /></span><span className="hidden sm:inline">Smriti</span><ChevronDown size={15} className="hidden text-muted-foreground sm:inline" /></button><button aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)} className="ml-1 lg:hidden"><Menu size={22} /></button></div>
      </header>
      {menuOpen && <div className="fixed inset-0 z-50 bg-[#23352a]/30 backdrop-blur-sm lg:hidden" onClick={() => setMenuOpen(false)}><div className="absolute right-0 top-0 h-full w-[280px] bg-background p-5 shadow-xl" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between"><Brand compact /><button onClick={() => setMenuOpen(false)}><X /></button></div><nav className="mt-8 space-y-1">{nav.map((item) => <button key={item.label} onClick={() => { setActive(item.label); setMenuOpen(false); }} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm"><item.icon size={18}/>{item.label}</button>)}</nav></div></div>}
      {active !== 'Today' && <FeaturePage active={active} />}
      <section className={`${active === 'Today' ? 'block' : 'hidden'} mx-auto max-w-[1180px] px-5 pb-28 pt-8 md:px-8 lg:px-10 lg:pb-10 lg:pt-10`}>
        <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.15em] text-[#83917f]">Your Tuesday</p><h1 className="font-heading text-[2rem] font-semibold leading-tight tracking-[-.03em] sm:text-[2.4rem]">Good morning, Smriti <span aria-hidden>🌱</span></h1><p className="mt-2 text-sm text-muted-foreground">A long day ahead. We’ll keep it simple and take it one step at a time.</p></div><div className="min-w-[180px] rounded-2xl border border-border bg-card px-4 py-3"><div className="flex items-center justify-between text-sm"><span className="font-medium">Today’s progress</span><span className="font-semibold text-primary">{percent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#e8ebe6]"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${percent}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">{completed} of {tasks.length} completed</p></div></div>
        <section aria-labelledby="next-action" className="relative overflow-hidden rounded-[26px] bg-[#284c3a] p-6 text-white shadow-[0_16px_45px_rgba(31,66,49,.16)] sm:p-8"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full border-[46px] border-white/[.035]"/><div className="relative grid gap-6 md:grid-cols-[1fr_auto] md:items-end"><div><div className="mb-5 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.18em] text-[#c4d6ca]"><Sparkles size={14}/> Next action</div><div className="flex gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white/10"><Pill size={23}/></span><div><h2 id="next-action" className="text-2xl font-semibold tracking-tight">{nextTask.title}</h2><p className="mt-1 text-sm text-[#c9d8cf]">Reshape Slimgal · 40 minutes before dinner</p><div className="mt-4 flex flex-wrap items-center gap-3 text-sm"><span className="flex items-center gap-1.5 font-medium"><Clock3 size={15}/> {snoozed ? '6:30 PM' : nextTask.time}</span><span className="rounded-full bg-white/10 px-2.5 py-1 text-xs">{snoozed ? 'Snoozed 10 min' : 'In 25 minutes'}</span></div></div></div></div><div className="flex gap-2 pl-16 md:pl-0"><button onClick={() => setSnoozed(true)} className="rounded-xl border border-white/20 px-4 py-2.5 text-sm font-semibold hover:bg-white/10">Snooze</button><button onClick={() => completeTask(nextTask.id)} className="flex items-center gap-2 rounded-xl bg-[#f4d6a3] px-5 py-2.5 text-sm font-bold text-[#294536] hover:bg-[#f8dfb5]"><Check size={17}/> Mark done</button></div></div></section>
        <div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.8fr)]"><section className="rounded-[22px] border border-border bg-card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Today’s flow</h2><p className="mt-1 text-xs text-muted-foreground">Only what matters next</p></div><button aria-label="More options" className="text-muted-foreground"><MoreHorizontal size={20}/></button></div><div className="space-y-1">{tasks.map((task) => { const Icon = taskIcons[task.icon]; return <button key={task.id} onClick={() => !task.done && completeTask(task.id)} className={`group flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-left transition hover:bg-[#f7f8f4] ${task.done ? 'opacity-55' : ''}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${task.done ? 'bg-[#dce8db] text-primary' : 'bg-[#f5f3ec] text-[#7a6e59]'}`}>{task.done ? <Check size={17}/> : <Icon size={17}/>}</span><span className="min-w-0 flex-1"><span className={`block text-sm font-semibold ${task.done ? 'line-through' : ''}`}>{task.title}</span><span className="block truncate text-xs text-muted-foreground">{task.detail}</span></span><time className="text-xs font-medium text-muted-foreground">{task.time}</time>{!task.done && <ChevronRight size={16} className="text-border transition group-hover:text-muted-foreground"/>}</button>})}</div><button className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-[#cbd2c8] py-3 text-sm font-semibold text-primary hover:bg-[#f7f8f4]"><Plus size={16}/> Add to today</button></section>
          <div className="space-y-6"><section className="rounded-[22px] border border-border bg-[#f7f2e9] p-5"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-[#587a96]"><Droplets size={19}/></div><span className="text-xs font-medium text-muted-foreground">Goal 2,000 ml</span></div><h2 className="mt-5 text-sm font-semibold">Hydration</h2><div className="mt-1 flex items-end justify-between"><p className="text-2xl font-semibold tracking-tight">{water.toLocaleString()} <span className="text-sm font-normal text-muted-foreground">ml</span></p><p className="text-xs text-muted-foreground">{Math.max(0, 2000-water)} ml to go</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-[#6e98ae] transition-all" style={{ width: `${Math.min(100,water/20)}%` }}/></div><button onClick={() => setWater((value) => Math.min(2000,value+250))} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-white py-2.5 text-sm font-semibold text-[#365d70] shadow-sm"><Plus size={16}/> Add 250 ml</button></section><section className="rounded-[22px] border border-border bg-card p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-medium text-muted-foreground">After that</p><h2 className="mt-1 text-sm font-semibold">Gentle evening walk</h2></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf2e9] text-primary"><HeartPulse size={19}/></span></div><div className="mt-4 flex items-center justify-between border-t border-border pt-4"><span className="text-xs text-muted-foreground">20 minutes · easy pace</span><span className="text-xs font-semibold">7:10 PM</span></div></section><button className="flex w-full items-center justify-between rounded-[22px] border border-border bg-card p-5 text-left"><span><span className="block text-xs font-medium text-muted-foreground">Daily check-in</span><span className="mt-1 block text-sm font-semibold">How are you feeling?</span></span><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#f1e4d5]">🙂</span></button></div>
        </div>
      </section>
      <nav aria-label="Mobile navigation" className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 border-t border-border bg-background/95 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur lg:hidden">{nav.map((item) => <button key={item.label} onClick={() => setActive(item.label)} className={`flex flex-col items-center gap-1 py-1 text-[10px] font-medium ${active === item.label ? 'text-primary' : 'text-muted-foreground'}`}><item.icon size={19} strokeWidth={active === item.label ? 2.3 : 1.8}/>{item.label}</button>)}</nav>
    </div>
  </main>;
}

function Brand({ compact = false }: { compact?: boolean }) { return <div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary text-white"><Leaf size={18} fill="currentColor"/></span>{!compact && <div><p className="text-lg font-bold leading-none tracking-[-.03em]">Saha</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[.13em] text-muted-foreground">your daily ally</p></div>}</div> }

const pageCopy: Record<string, { eyebrow: string; title: string; intro: string }> = {
  Plan: { eyebrow: 'Your routine', title: 'Plan a day that fits real life', intro: 'Meals, college and rest—gently arranged around the energy you actually have.' },
  Track: { eyebrow: 'Daily wellbeing', title: 'A quick check-in with yourself', intro: 'Notice patterns without judging the day or turning every feeling into a number.' },
  Medicines: { eyebrow: 'Medication center', title: 'Your medicines, clearly organized', intro: 'Reminder and tracking only. Always follow your prescription or clinician’s instructions.' },
  Insights: { eyebrow: 'This week', title: 'Seven days of showing up', intro: 'Small patterns to help make next week feel a little easier.' },
};

function FeaturePage({ active }: { active: string }) {
  const copy = pageCopy[active];
  return <section className="mx-auto max-w-[1180px] px-5 pb-28 pt-8 md:px-8 lg:px-10 lg:pb-10 lg:pt-10">
    <p className="text-xs font-semibold uppercase tracking-[.15em] text-[#83917f]">{copy.eyebrow}</p><h1 className="mt-2 text-[2rem] font-semibold tracking-[-.03em] sm:text-[2.4rem]">{copy.title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{copy.intro}</p>
    {active === 'Plan' && <PlanPage />}{active === 'Track' && <TrackPage />}{active === 'Medicines' && <MedicinesPage />}{active === 'Insights' && <InsightsPage />}
  </section>;
}

function PlanPage() {
  const meals = [['Breakfast','Moong dal chilla + curd','6:50 AM'],['College lunch','Paneer roti roll + cucumber','12:45 PM'],['Travel snack','Makhana + almonds','4:15 PM'],['Dinner','Jain paneer bowl + roti','7:40 PM']];
  return <div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-[22px] border bg-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Tuesday meal plan</h2><p className="mt-1 text-xs text-muted-foreground">Jain vegetarian · college day</p></div><button className="rounded-xl border px-3 py-2 text-xs font-semibold">Swap meal</button></div><div className="mt-5 space-y-2">{meals.map(([label,meal,time],i)=><div key={label} className="flex items-center gap-4 rounded-2xl bg-[#f7f8f4] p-4"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-primary"><Utensils size={17}/></span><span className="min-w-0 flex-1"><span className="block text-xs text-muted-foreground">{label}</span><span className="block truncate text-sm font-semibold">{meal}</span></span><time className="text-xs font-medium text-muted-foreground">{time}</time></div>)}</div></section><div className="space-y-6"><section className="rounded-[22px] bg-[#eaf1e4] p-5"><p className="text-xs font-semibold uppercase tracking-wider text-[#6d806f]">Your Jain preferences</p><h2 className="mt-2 text-lg font-semibold">Onion & garlic excluded</h2><p className="mt-2 text-sm text-muted-foreground">Root vegetables are allowed in your current preferences.</p><button className="mt-5 text-sm font-semibold text-primary">Edit preferences →</button></section><section className="rounded-[22px] border bg-card p-5"><p className="text-xs text-muted-foreground">Tomorrow starts at</p><p className="mt-1 text-2xl font-semibold">5:45 AM</p><div className="mt-4 space-y-2 text-sm"><p className="flex justify-between"><span>Leave home</span><strong>7:00 AM</strong></p><p className="flex justify-between"><span>College</span><strong>9:00 AM</strong></p><p className="flex justify-between"><span>Expected home</span><strong>6:00 PM</strong></p></div></section></div></div>;
}

function TrackPage() {
  const [energy,setEnergy]=useState(3); const [mood,setMood]=useState(4); const [symptoms,setSymptoms]=useState<string[]>([]); const options=['Bloating','Acne','Cramps','Fatigue','Headache','Body pain'];
  return <div className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-[22px] border bg-card p-5 sm:p-7"><h2 className="text-lg font-semibold">How are you feeling today?</h2><p className="mt-1 text-sm text-muted-foreground">This stays private and takes less than a minute.</p><Scale label="Energy" value={energy} setValue={setEnergy}/><Scale label="Mood" value={mood} setValue={setMood}/><div className="mt-7"><p className="text-sm font-semibold">Anything you noticed?</p><div className="mt-3 flex flex-wrap gap-2">{options.map(o=><button key={o} onClick={()=>setSymptoms(v=>v.includes(o)?v.filter(x=>x!==o):[...v,o])} className={`rounded-full border px-3.5 py-2 text-sm ${symptoms.includes(o)?'border-primary bg-[#e9f1df] text-primary':'bg-white text-muted-foreground'}`}>{symptoms.includes(o)&&'✓ '}{o}</button>)}</div></div><button className="mt-8 w-full rounded-xl bg-primary py-3 text-sm font-bold text-white">Save check-in</button></section><div className="space-y-6"><MetricCard icon={<Moon size={19}/>} title="Sleep" value="6h 45m" note="45 min below your target"/><MetricCard icon={<HeartPulse size={19}/>} title="Movement" value="20 min" note="A gentle walk is planned"/><div className="rounded-[22px] bg-[#f7f2e9] p-5 text-sm leading-relaxed text-muted-foreground"><strong className="block text-foreground">A note from Saha</strong><span className="mt-2 block">Tracking helps you notice patterns. It does not diagnose a condition or replace professional care.</span></div></div></div>;
}

function Scale({label,value,setValue}:{label:string;value:number;setValue:(n:number)=>void}) { return <div className="mt-7"><div className="flex justify-between text-sm"><span className="font-semibold">{label}</span><span className="text-muted-foreground">{value}/5</span></div><div className="mt-3 grid grid-cols-5 gap-2">{['😫','😕','😐','🙂','😊'].map((face,i)=><button key={face} onClick={()=>setValue(i+1)} aria-label={`${label} ${i+1} of 5`} className={`rounded-xl border py-3 text-xl ${value===i+1?'border-primary bg-[#e9f1df]':'bg-white'}`}>{face}</button>)}</div></div> }
function MetricCard({icon,title,value,note}:{icon:React.ReactNode;title:string;value:string;note:string}) { return <section className="rounded-[22px] border bg-card p-5"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf2e9] text-primary">{icon}</span><span className="text-xs text-muted-foreground">Today</span></div><h2 className="mt-4 text-sm font-semibold">{title}</h2><p className="mt-1 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></section> }

function MedicinesPage() {
  const meds=[['Reshape Slimgal','Twice daily · 40 min before food','6:10 AM · 6:20 PM','Active'],['Cinafen','Twice daily · 40 min before food','6:10 AM · 6:20 PM','Active'],['Midi Ova Inoset Forte','Twice daily · after food','7:10 AM · 8:15 PM','Active'],['Estramit-35','Once at night · after food','9:00 PM','21-day course'],['Monteklast','Once at night · after food','9:00 PM','Long term']];
  return <div className="mt-8"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">5 active medicines · 8 reminders today</p><button className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-white"><Plus size={16}/> Add medicine</button></div><div className="grid gap-3">{meds.map(([name,instruction,time,status])=><section key={name} className="grid items-center gap-4 rounded-[20px] border bg-card p-5 sm:grid-cols-[auto_1fr_auto_auto]"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#eaf1e4] text-primary"><Pill size={20}/></span><div><h2 className="text-sm font-semibold">{name}</h2><p className="mt-1 text-xs text-muted-foreground">{instruction}</p></div><div className="sm:text-right"><p className="text-xs font-semibold">{time}</p><p className="mt-1 text-xs text-muted-foreground">Reminder on</p></div><span className="w-fit rounded-full bg-[#edf3e9] px-3 py-1 text-[11px] font-semibold text-primary">{status}</span></section>)}</div><p className="mt-6 rounded-2xl border border-[#eadfce] bg-[#fcf8f1] p-4 text-xs leading-relaxed text-muted-foreground">Saha never changes dosage, duration or medical instructions. Medicine details should always be entered and verified from your prescription or healthcare professional.</p></div>;
}

function InsightsPage() {
  const rows=[['Medication','86%',86],['Meals logged','71%',71],['Hydration','79%',79],['Movement','57%',57],['Sleep target','64%',64]];
  return <div className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-[22px] border bg-card p-5 sm:p-7"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Routine consistency</h2><p className="mt-1 text-xs text-muted-foreground">A routine indicator—not a medical score</p></div><div className="text-right"><p className="text-3xl font-semibold text-primary">74%</p><p className="text-[11px] text-muted-foreground">this week</p></div></div><div className="mt-7 space-y-5">{rows.map(([label,val,n])=><div key={label}><div className="mb-2 flex justify-between text-sm"><span>{label}</span><strong>{val}</strong></div><div className="h-2 rounded-full bg-[#edf0eb]"><div className="h-full rounded-full bg-primary" style={{width:`${n}%`}}/></div></div>)}</div></section><div className="space-y-6"><section className="rounded-[22px] bg-[#eaf1e4] p-5"><p className="text-xs font-semibold uppercase tracking-wider text-[#6d806f]">Your wins 🌱</p><ul className="mt-4 space-y-3 text-sm"><li>✓ Morning medication improved</li><li>✓ Hydration improved on college days</li><li>✓ 4 days with intentional movement</li></ul></section><section className="rounded-[22px] border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">One thing to ease</p><h2 className="mt-3 text-base font-semibold">Evening reminders overlap your commute</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">You marked “travelling” twice this week. Would 15 minutes later feel more realistic?</p><div className="mt-5 flex gap-2"><button className="rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-white">Review time</button><button className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Keep schedule</button></div></section></div></div>;
}
